### PR TITLE
Tutorial

### PR DESCRIPTION
**Pull request by SamLau95**
As the title says, this is the tutorial that will be shown on the homepage of the `datascience` docs.

Finishes #150 .
Closes #111 .

### CODE REVIEW

**Comment by SamLau95** [comment]
@stefanv It looks like Travis is complaining about an `Invalid DISPLAY variable`.
Have you run into this issue before? I'm calling `matplotlib.use("Agg", warn=False)`
in `conf.py`.

**Comment by deculler** [comment]
Might want to use some simple list comprehensions to initialize tables so
people are not faced with numpy early.

**Comment by SamLau95** [comment]
@deculler The only example I have of using

**Comment by stefanv** [comment]
Sorry, Sam, I am not in front of a computer right now, but if you have a
look in the scikit-image Travis script you can look at how we set it up.

**Comment by SamLau95** [comment]
Phew, the build finally passes and I'm going to merge this now.

On the plus side, I figured out why caching wasn't working properly so new builds should only take a couple minutes to run.

**Comment by stefanv** [comment]
Good work, thanks Sam!

Were changes like ``to_csv`` etc. intended to be part of this PR? All  changes seem fine, though.

**Comment by SamLau95** [comment]
They were part of previous PRs that I rebased into the tutorial branch.
Github isn't really smart about rebasing onto a PR but I think the history
should still be right on master.

**Pull request merged**
