### PR TITLE
Histogram of counts and bin method

### PR DESCRIPTION
**Pull request by papajohn**

### CODE REVIEW

**Comment by papajohn** [comment]
Say you have a two column table of values:

screen shot 2015-09-27 at 11 14 48 am

You can draw an overlain histogram (thanks Sam — this PR fixes a weird legend labeling issue):

screen shot 2015-09-27 at 11 15 44 am

Now you can also bin all values to create a table of counts:

screen shot 2015-09-27 at 11 16 24 am

And a table that contains multiple columns of counts for the same values (or ranges) can be plotted as a histogram. Note that this changes the behavior of the `counts` argument of `hist` to actually make sense... now you pass the column of values that are counted rather than the column of counts.

screen shot 2015-09-27 at 11 17 53 am

**Comment by papajohn** [comment]
Resolves #54

**Comment by SamLau95** [comment]
This looks great! Thanks John.

**Comment by deculler** [comment]
Looks like we can discard the table2hist branch.  bin does a better job of
creating a histogram table.

David E. Culler
Friesen Professor of Computer Science
Electrical Engineering and Computer Sciences
University of California, Berkeley

**Pull request merged**
