### PR TITLE
Clean versioning

### PR DESCRIPTION
**Pull request by stefanv**

### CODE REVIEW

**Comment by SamLau95** [comment]
This is much better than what we had before! Will a version like `0.3.dev13` be considered more up-to-date than `0.3.12` transparently?

**Comment by ryanlovett** [comment]
0.3.14 is already up on pypi and is greater than this commit's 0.3.dev13. (or is it?)

**Comment by stefanv** [comment]
I guess someone forgot to update the version number.  I'll update it here.

**Comment by stefanv** [comment]
Also see https://www.python.org/dev/peps/pep-0440/#developmental-releases

**Comment by papajohn** [comment]
Nifty.

**Pull request merged**
