### PR TITLE
Add percentile function to Table

### LINKED ISSUE #37: Implement a percentile function
The pth percentile of a list is the smallest number that is at least as large as p% of the numbers in the list.

That means: sort the list from low to high, go p% up the list from the bottom. If you're at a place on the list, take its value. Else take the next one.

### PR DESCRIPTION
**Pull request by SamLau95**
```
>>> print(table)
letter | count | points
a      | 9     | 1
b      | 3     | 2
c      | 3     | 2
z      | 1     | 10

>>> table.percentile('count', 70)
9
>>> table.percentile('count', 50)
3
```

Verified that `python setup.py test` works.
Resolves #37.

### CODE REVIEW

**Comment by papajohn** [comment]
Great! What do you think of making the interface like `sum`, in that it returns a one-row table with the stat computed for each column.

Also, we should add a higher-order `percentile` function that takes a percentage and returns a function on arrays. That way, we could pass it into `Table.stats`. E.g., `t.stats([np.sum, len, percentile(25)])`, perhaps.

```
>>> print(t)
a
1
2
3
>>> print(t.sum())
a
6
```

**Comment by papajohn** [comment]
Actually, maybe it's not crazy to make the `percentile` function currying on one arg (a percent) but compute the percentile value on two args (a percent and an array).

**Comment by SamLau95** [comment]
@papajohn could you clarify your last comment? Should I still add a `percentile` function at the top level?

Also, the build is failing because of `test_date_format` (https://travis-ci.org/dsten/datascience/builds/74514799), which doesn't seem related to my diff. `python setup.py test` passes on my machine.

**Comment by papajohn** [comment]
The build failure is some version error we don't understand (or maybe time
stamps aren't consistent.

Yes, I think there should be a top level percentile function.

**Comment by SamLau95** [comment]
I added a `util` module and implemented a `percentile` function there. One way to use it for `Table.stats` is to use `functools.partial`. Or, we could add a partial'd function from `util` as well. Any opinions?

**Comment by papajohn** [comment]
I think we just write

def percentile(n, vs=None):
  if vs is None:
    return lambda vs: percentile(n, vs)
  # your implemention assuming vs is a sequence
  return some_number

Yes, functools.partial is the standard answer, but it's not a good fit for
this class.

-John

**Comment by deculler** [comment]
Wouldn't it make sense to be able to pass in a vector of p's, in order, and
produce a row for each value of the other?

David E. Culler
Friesen Professor of Computer Science
Electrical Engineering and Computer Sciences
University of California, Berkeley

**Comment by SamLau95** [comment]
@papajohn Thoughts on David's suggestion? You have more context as to whether that functionality would be useful for students.

**Comment by a-adhikari** [comment]
I like it. We'll need p = 0.25, 0.5, 0.75 for box plots anyway.
Ani

On Thu, Aug 20, 2015 at 12:03 AM, Sam Lau <notifications@github.com> wrote:

> @papajohn <https://github.com/papajohn> Thoughts on David's suggestion?
> You have more context as to whether that functionality would be useful for
> students.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dsten/datascience/pull/40#issuecomment-132913357>.
>



-- 
Ani Adhikari
Teaching Professor
Department of Statistics
University of California, Berkeley

**Comment by papajohn** [comment]
That sounds reasonable to me.

**Pull request merged**
