### PR TITLE
Make hist overlay actually overlap bars on top of each other

### LINKED ISSUE #65: Overlain histograms need to have the correct bin widths; overlap instead of side-by-side

### PR DESCRIPTION
**Pull request by SamLau95**
Resolves #65 .

Here's some sample output:

```python
>>> dist1 = np.random.normal(0, 1, 300)
>>> dist2 = np.random.normal(1, 1, 300)
>>> dist3 = np.random.normal(3, 1, 300)
>>> t = Table([dist1, dist2, dist3], ['dist1', 'dist2', 'dist3'])
>>> print(t)
dist1      | dist2    | dist3
-0.247325  | 0.81949  | 4.15663
-0.902479  | 0.731966 | 2.8134
3.19281    | 1.92821  | 2.23576
0.870155   | 0.280848 | 2.79061
-1.25049   | 0.366729 | 3.99718
0.106276   | 1.45144  | 3.472
-0.955269  | 1.51157  | 4.34933
-1.10473   | 1.60643  | 4.36868
-0.926389  | 0.734534 | 1.75524
0.00759599 | 0.353553 | 3.8072
... (290 rows omitted)

>>> t.hist(overlay=True)

```

screenshot 2015-09-26 19 40 52

### CODE REVIEW

**Comment by SamLau95** [comment]
@a-adhikari needs this ASAP — @papajohn: after this is merged, could you push this to Pypi and ping Ryan to update the library version on Juypter? Thanks!

**Comment by a-adhikari** [comment]
Sam, this is terrific! Three histograms is one more than I had expected;
just two would have been fine :)

Now all we need is for this to work with hist operating on counts and bins,
but surely that's OK already. I'll send you the data I'm planning to use
for the lectures.

Thanks so much,

Ani

On Sat, Sep 26, 2015 at 7:43 PM, Sam Lau <notifications@github.com> wrote:

> @a-adhikari <https://github.com/a-adhikari> needs this ASAP — @papajohn
> <https://github.com/papajohn>: after this is merged, could you push this
> to Pypi and ping Ryan to update the library version on Juypter? Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dsten/datascience/pull/84#issuecomment-143513820>.
>



-- 
Ani Adhikari
Teaching Professor
Department of Statistics
University of California, Berkeley

**Comment by papajohn** [comment]
Looks great. Thanks, Sam!

**Comment by ryanlovett** [comment]
I updated the singleuser image to 0.3.10 last night.

**Pull request merged**
