### PR TITLE
Provide new minimal representation for row

### PR DESCRIPTION
**Pull request by mDibyo**
A row was earlier represented as a namedtuple. But this resulted in
the restriction that a table could not have more than 255 columns
(see http://stackoverflow.com/questions/18550270/any-way-to-bypass-namedtuple-255-arguments-limitation).

The new representation is a subclass of tuple which still
approximately provides access to column labels and has the same
representation. Additionally, column values can be accessed as
attributes and a mapping from column label to values can be obtained
using the asdict() method. Other behavior can be filled in as
required.

### CODE REVIEW

**Comment by mDibyo** [comment]
This PR fixes #46.

**Comment by mijordan3** [comment]
A bit more info on what we're thinking to do with the lyrics dataset:

Each row is a song.  The columns are the words, and the entry in a given
(row, column) is the number of times that
that word appears in the song.  (Perhaps normalized).  The final column is
the label of the genre.  We're doing two genres,
so it will be binary.

Part I:  To classify a song, we define a distance metric between rows,
presumably just Euclidean distance.
We then find the K nearest rows to the row representing the song we're
classifying, for K fixed a apriori (to, say 10).
Look up the class labels in the final column for those K nearest rows.
Take a vote over the binary labels
to label the query song.  Use a held-out test set to evaluate how well this
algorithm does.

Part II:  Use a third set of data, the cross-validation set, to try out
various values of K.  Find the winner in terms
of classification accuracy on the cross-validation set, and then fix that
value of K to classify the held-out test set.

Part III:  Find the single word that is most discriminative for this task.
I.e., from the original data, select a single
word column and redo Part I using that single column (together with the
label column).  Loop over the 5000 columns
and find the best predictor (on the cross-validation set).

So this project (and many similar projects in data science) require rows to
be first-class citizens.

Mike

**Comment by deculler** [comment]
This looks great.  I'm so glad that you added asdict.  Conceptually, it is
natural to view rows as a 'record' as they used to say.

I did a one slide version of tables today for a talk at the Data Science
Environments workshop in the morning.  I've attached it here.  With this
PR, the little white lie went away.

David E. Culler
Friesen Professor of Computer Science
Electrical Engineering and Computer Sciences
University of California, Berkeley

**Comment by deculler** [comment]
If I've got it right, 5,000 is the words in the dictionary. You probably
want to think of each song as a column.  Not only can you name the columns
with the song names, it will be a couple orders of magnitude faster. And
you can control what you need to cope with by deciding how large a library
to include.  It is harder to leave out words.

Tables fundamentally are a ordered collection of named columns.  Columns
are numpy arrays.  Rows are not.  Not by a long ways.  And you have the
full power of numpy built in on columns.

Or for us old guys, think Fortran, not C.

David E. Culler
Friesen Professor of Computer Science
Electrical Engineering and Computer Sciences
University of California, Berkeley

**Comment by mijordan3** [comment]
We're going to be wanting to work with tens of thousands of songs.  Will
the representation support that
number of columns?

And will it be easy to loop over rows in the feature selection problem?

(I'm confused at this point, because I thought that we were working with a
paradigm in which data points are rows.
The songs are the data points in this problem.)

M

**Comment by mDibyo** [comment]
The current representation will support unlimited columns and rows (within memory bounds. )

Looping over rows is possible (`for row in table.rows`) but is a slower process. Looping over rows is a faster process. To elaborate, the table currently is backed by an array of vectors, wherein each vector holds a column. (basically, as @deculler mentioned, Fortran and not C) A row is obtained by stringing together the corresponding value from each of these vectors. This is also part of the reason why we have a wrapper to represent the Row, while we don't have one for columns.

So, we would want our data points to be columns.

It might be possible to add a switch to Table which when 'on' makes our table an array of rows. This would not change the table interface, only change the way operations are handled internally. If done right, it would only require minor changes to the code. If we do this, we could support data points as rows. @papajohn, what do you think?

**Comment by papajohn** [comment]
I think supporting multiple implementations will complicate table.py more
than I'd like, so I'd rather have row access be slow for now.

**Comment by papajohn** [comment]
I think it should be no problem to loop over 10k rows many times in this implementation. merging.

**Comment by deculler** [comment]
Agree on that.

**Pull request merged**
